name: VyPrisons
version: 1.0
api-version: 1.16
main: com.glitchedturtle.vyprisons.VyPrisonPlugin
depend:
  - WorldEdit
softdepend:
  - AutoSell
commands:
  vyprison:
    description: "VyPrison main command"
    aliases: [ "vyp" ]